### ISSUE TITLE
`setup_zone` fails for a zone with 3 parts

### ISSUE THREAD

**Issue by samueljsb** [ailionx/cloudflare-ddns#13]
My domain (samueljsb.co.uk) can't be used through this library because it cuts off the front part and tries to connect with `.co.uk` (https://github.com/ailionx/cloudflare-ddns/blob/05128d498830909792090764e854e789cec79283/cloudflare_ddns/cloudflare.py#L99)

Why does this method chop up the domain like this?

**Comment by isaacnoboa** [comment]
I'm guessing it's to separate subdomains (www.example.com) from the domain+TLD combination (www.example.com). In my use case (where i wanted to update www.subdomain.example.com, and the function chopper was pulling "subdomain.example.com" instead of "example.com", I fixed it by adding an elif clause for a four-part domain name:

```python
            if len(self.domain.split('.')) == 3:
                domain = self.domain.split('.', 1)[1]
            elif len(self.domain.split('.')) == 4:
                domain = self.domain.split('.', 2)[2]
            else:
                domain = self.domain
```

In your use-case, I'd imagine you'd want it to have a special case for .co.uk, so that .com domains can continue to work normally, so something like this might work:

```python
            if len(self.domain.split('.')) == 3 and self.domain.split('.', 1)[1] != "co.uk"
                domain = self.domain.split('.', 1)[1]
            else:
                domain = self.domain
```

If I figure out a way to handle two-level subdomains correctly while also handling two-level TLDs, without hardcoding every single double TLD out there, I'll submit a pull request.

**Comment by unicodepepper** [comment]
This pull request should fix that issue for both of our use cases:

https://github.com/ailionx/cloudflare-ddns/pull/14

**Comment by isaacnoboa** [comment]
This pull request should fix that problem for both use cases:

https://github.com/ailionx/cloudflare-ddns/pull/14

**Comment by samueljsb** [comment]
Looks like #14 has indeed solved this, thanks @unicodepepper !
